name: "crick'd"
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#18222c'
    - '#668341'
    - '#8e9eaf'
    - '#f6fbff'
    - '#415538'
  brandStrength: 0.8125
  lightness: 0.9375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
